name: ci

on:
  push:
    branches:
      - 'main'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Get docker image version
      id: vars
      run: echo "version=$(cat docker_image_version)" >> $GITHUB_OUTPUT
   
    - name: Test output
      run: echo ${{ steps.vars.outputs.version }}
    
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: bhagyesh19/static-site
        tags: ${{ steps.vars.outputs.version }}
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
