name: ci

on:
  push:
    branches:
      - 'main'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Get docker image version
      run: |
        ls -al
        pwd
   
    - name: Test output
      run: echo ${{ steps.vars.outputs.version }}
