name: ci

on:
  push:
    branches:
      - 'main'


jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Get docker image version
      id: vars
      run: echo ::set-output name=version::$(cat docker_image_version)
   
    - name: Test output
      run: echo ${{ steps.vars.outputs.version }}
